// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

declare type BaseDisplay = { __type: string }
declare type DisplayFor<T> = BaseDisplay & T

declare type CommandItem = { __type: "COMMAND", id: string, name: string }
declare type ErrorItem = { __type: "ERROR", message: string }

declare namespace launcher {
    function search(input: string): Promise<DisplayFor<unknown>[]>
    function execute(id: string): Promise<DisplayFor<unknown>[]>
    function close(): Promise<void>
}